[package]
name = "alpha-makemore-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"

[dev-dependencies]
alpha-micrograd-rust = "0.3.1"
clap = { version = "4.5.32", features = ["derive"] }
indicatif = "0.17.11"
